"""commit message

Revision ID: 39de58f1159a
Revises: 9f097d8895de
Create Date: 2024-11-12 14:39:04.540731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39de58f1159a'
down_revision = '9f097d8895de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.drop_column('slug1')
        batch_op.drop_column('id1')
        batch_op.drop_column('title1')
        batch_op.drop_column('content1')
        batch_op.drop_column('author1')
        batch_op.drop_column('date_posted1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted1', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('author1', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('content1', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('title1', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('id1', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('slug1', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('slug')
        batch_op.drop_column('date_posted')
        batch_op.drop_column('author')
        batch_op.drop_column('content')
        batch_op.drop_column('title')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
