"""commit message

Revision ID: 690cdaee6f7d
Revises: 0784954e45c7
Create Date: 2024-11-12 14:37:16.438070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '690cdaee6f7d'
down_revision = '0784954e45c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('new_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_field', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
