"""commit message

Revision ID: 9f097d8895de
Revises: 690cdaee6f7d
Create Date: 2024-11-12 14:38:26.587110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f097d8895de'
down_revision = '690cdaee6f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('content1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('author1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_posted1', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('slug1', sa.String(length=255), nullable=True))
        batch_op.drop_column('id')
        batch_op.drop_column('date_posted')
        batch_op.drop_column('author')
        batch_op.drop_column('title')
        batch_op.drop_column('content')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('author', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_posted', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('slug1')
        batch_op.drop_column('date_posted1')
        batch_op.drop_column('author1')
        batch_op.drop_column('content1')
        batch_op.drop_column('title1')
        batch_op.drop_column('id1')

    # ### end Alembic commands ###
